using System.Collections.Generic;
using Prompts;

namespace IOHandlers.Records
{
	public static class DefaultRecordsCreator
	{	
		public static List<WayPointRecord> AddDefaultWayPointsRecords()
     		{
     			var records = new List<WayPointRecord>()
     			{
     				new () { Id = 0, Position = { X = 200f, Y = 100, Z = 800 } },
     				new () { Id = 1, Position = { X = 400, Y = 100, Z = 800 } },
     				new () { Id = 2, Position = { X = 600,Y = 100, Z = 800 } },
     				new () { Id = 3, Position = { X = 800,Y = 100, Z = 800} },
     
     				new () { Id = 4, Position = { X = 200, Y = 100, Z = 600 } },
     				new () { Id = 5, Position = { X = 400, Y = 100, Z = 600 } },
     				new () { Id = 6, Position = { X = 600, Y = 100, Z = 600 } },
     				new () { Id = 7, Position = { X = 800, Y = 100, Z = 600 } },
     
     				new () { Id = 8, Position = { X = 200, Y = 100, Z = 400 } },
     				new () { Id = 9, Position = { X = 400, Y = 100, Z = 400 } },
     				new () { Id = 10, Position= { X = 600, Y = 100, Z = 400 } },
     				new () { Id = 11, Position= { X = 800, Y = 100, Z = 400 } },
     
     				new () { Id = 12, Position = { X = 200, Y = 100, Z = 200 } },
     				new () { Id = 13, Position = { X = 400, Y = 100, Z = 200 } },
     				new () { Id = 14, Position = { X = 600, Y = 100, Z = 200 } },
     				new () { Id = 15, Position = { X = 800, Y = 100, Z = 200 } },
     			};
     			return records;
     		}
     
     		public static SettingsRecord GetDefaultSettings()
     		{
     			var record = new SettingsRecord()
     			{
     				TimePeriodDurationInSecs = 10,
     				SceneName = "GridWayPoints",
     				TargetSpawnBufferRange = new Range() { Min = 5, Max = 7 },
     				EnableFuelLeaks = true,
     				BlankCamerasBetweenNavigations = false
     
     			};
     
     			return record;
     		}

		public static List<UavRecord> AddDefaultUavRecords()
		{
			var records = new List<UavRecord>()
			{
				new () { Id = 0, StartingWayPointId = 4, EnabledOnStart = false },
				new () { Id = 1, StartingWayPointId = 7, EnabledOnStart = false },
				new () { Id = 2, StartingWayPointId = 10, EnabledOnStart = false },
				new () { Id = 3, StartingWayPointId = 2, EnabledOnStart = false },
				new () { Id = 4, StartingWayPointId = 9, EnabledOnStart = true },
				new () { Id = 5, StartingWayPointId = 1, EnabledOnStart = false },
				new () { Id = 6, StartingWayPointId = 11, EnabledOnStart = false },
				new () { Id = 7, StartingWayPointId = 6, EnabledOnStart = false },
				new () { Id = 8, StartingWayPointId = 14, EnabledOnStart = false },
				new () { Id = 9, StartingWayPointId = 9, EnabledOnStart = true },
				new () { Id = 10, StartingWayPointId = 5, EnabledOnStart = false },
				new () { Id = 11, StartingWayPointId = 0, EnabledOnStart = false },
				new () { Id = 12, StartingWayPointId = 8, EnabledOnStart = false },
				new () { Id = 13, StartingWayPointId = 13, EnabledOnStart = false },
				new () { Id = 14, StartingWayPointId = 14, EnabledOnStart = false },
				new () { Id = 15, StartingWayPointId = 13, EnabledOnStart = true }
			};
			return records;
		}

	
		public static List<UavFuelLeaksRecord> AddDefaultFuelLeaksRecord()
		{
			var records = new List<UavFuelLeaksRecord>()
			{
				new () { UavID = 0, FuelLeakTimes = new List<float>() {179f} },
				new () { UavID = 2, FuelLeakTimes = new List<float>(){863} },
				new () { UavID = 3, FuelLeakTimes = new List<float>(){275f,471f} },
				new () { UavID = 4, FuelLeakTimes = new List<float>(){693f} },
				new () { UavID = 6, FuelLeakTimes = new List<float>(){432f} },
				new () { UavID = 7, FuelLeakTimes = new List<float>(){721f} },
				new () { UavID = 8, FuelLeakTimes = new List<float>(){85f,255f} },
				new () { UavID = 12, FuelLeakTimes =new List<float>() {841f} },
				new () { UavID = 13, FuelLeakTimes =new List<float>() {44f,626f} },
				new () { UavID = 14, FuelLeakTimes = new List<float>(){349f} },
			};

			return records;
		}

		public static List<UavPathsRecord> AddDefaultUavPathsRecords()
		{
			var records = new List<UavPathsRecord>()
			{
				new()
				{
					UavId= 0,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{	
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 11	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	,TargetIsPresent =	true}
					}
				},
				new()
				{
				UavId= 1,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID =3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =6	},
						new(){ DestinationWayPointID =7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =10,  UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =14,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =10,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =7	},
						new(){ DestinationWayPointID =6	},
						new(){ DestinationWayPointID =5	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =4	},
						new(){ DestinationWayPointID =0	},
						new(){ DestinationWayPointID =1	},
						new(){ DestinationWayPointID =2	},
						new(){ DestinationWayPointID =3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =2	},
						new(){ DestinationWayPointID =1	},
						new(){ DestinationWayPointID =0	},
						new(){ DestinationWayPointID =4	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =5	},
						new(){ DestinationWayPointID =6	},
						new(){ DestinationWayPointID =7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =10,  UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =10,  UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =4	},
						new(){ DestinationWayPointID =0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =1	},
						new(){ DestinationWayPointID =2	},
						new(){ DestinationWayPointID =3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =2	},
						new(){ DestinationWayPointID =1	},
						new(){ DestinationWayPointID =0	},
						new(){ DestinationWayPointID =4	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =5	},
						new(){ DestinationWayPointID =6	},
						new(){ DestinationWayPointID =7	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =10,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =10,  UavVisuallyEnabled =	true	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =7, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =5	},
						new(){ DestinationWayPointID =4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =1	},
						new(){ DestinationWayPointID =2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =1	},
						new(){ DestinationWayPointID =0, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =4	},
						new(){ DestinationWayPointID =5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =6	},
						new(){ DestinationWayPointID =7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =10,  UavVisuallyEnabled =	true	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =8, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =10,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =9,  UavVisuallyEnabled =	true	},
						new(){ DestinationWayPointID =7	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =6	},
						new(){ DestinationWayPointID =5	},
						new(){ DestinationWayPointID =4	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =0	},
						new(){ DestinationWayPointID =1	},
						new(){ DestinationWayPointID =2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID =3	},
						new(){ DestinationWayPointID =2, UavVisuallyEnabled =	false	}
					}
				},
				new()
				{
				UavId= 2,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	}
					}
				},
				new()
				{
				UavId= 3,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 11	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 6	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	}
					}
				},
				new()
				{
				UavId= 4, 
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	}
					}
				},
				new()
				{
				UavId= 5, 
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 12	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
					}
				},
				new()
				{
				UavId= 6, 
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 4	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	,TargetIsPresent =	true},

					}
				},
				new()
				{
				UavId= 7,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 10	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 10	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
					}
				},
				new()
				{
				UavId= 8, 
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 10	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 10	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 15	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 7	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 5	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 10	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
					}
				},
				new()
				{
				UavId= 9, 
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
					}
				},
				new()
				{
				UavId= 10, 
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 14	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 5	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
					}
				},
				new()
				{
				UavId= 11,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 0	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 1	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 1	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0	},
						new(){ DestinationWayPointID = 1	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
					}
				},
				new()
				{
				UavId= 12,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 10	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
					}
				},
				new()
				{
				UavId= 13,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 5	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 5	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 2	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 8	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
					}
				},
				new()
				{
				UavId= 14,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 5	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 6	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 5	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 15	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 7, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 2, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 3	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 11	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 13	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 11	},
						new(){ DestinationWayPointID = 7	},
						new(){ DestinationWayPointID = 3	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 1	},
						new(){ DestinationWayPointID = 6	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 10	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
					}
				},
				new()
				{
				UavId= 15,
					PathRecords = new List<UavPathsRecord.PathRecord>()
					{
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 0, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	,TargetIsPresent =	true},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 6, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12	},
						new(){ DestinationWayPointID = 4	},
						new(){ DestinationWayPointID = 13	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 12, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 9, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 8, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 10, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 5	},
						new(){ DestinationWayPointID = 4, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 13, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15	},
						new(){ DestinationWayPointID = 14, UavVisuallyEnabled =	false	},
						new(){ DestinationWayPointID = 15, UavVisuallyEnabled =	false	}
					}
				}
			};
			return records;
		}


		public static List<Prompt> GetDefaultPrompts()
		{
			var messages = new List<Prompt>()
			{
				new()
				{
					timeToPresent = 0,
					durationToAcceptResponses = 0,
					consoleMessage = new()
					{text = "beginning Mission",
					color = "Yellow"}
				},
				new()
				{
					timeToPresent = 15,
					durationToAcceptResponses = 0,
					consoleMessage = new()
					{
						text = "Which UAV/s had a bad projected route?",
						color = "red",
					},
					acceptMultipleResponses = true,
					responseOptions = new List<ResponseOption>()
					{
						new() { buttonText = "#0"  },
						new () { buttonText = "#1" },
						new () { buttonText = "#2" },
						new () { buttonText = "#3" },
						new () { buttonText = "#4" },
						new () { buttonText = "#5" },
						new () { buttonText = "#6" },
						new () { buttonText = "#7" },
						new () { buttonText = "#8" },
						new () { buttonText = "#9" },
						new () { buttonText = "#10", isCorrectResponse = true },
						new () { buttonText = "#11" },
						new () { buttonText = "#12" },
						new () { buttonText = "#13" },
						new () { buttonText = "#14" },
						new () { buttonText = "#15" },
						
					}
				},
				new()
				{
					timeToPresent = 22,
					durationToAcceptResponses = 10,
					consoleMessage = new()
					{text = "Detecting UAV 6 flying away from NFZ?",
					color = "Yellow"},
					acceptMultipleResponses = false,
					responseOptions = new List<ResponseOption>()
					{
						new ()
						{
							buttonText = "Confirm",
							buttonColor = "Green",
							isCorrectResponse = true
						},
						new ()
						{
							buttonText = "Deny",
							buttonColor = "Red",
							isCorrectResponse = false
						},
					}
				},
				new()
				{
					timeToPresent = 129,
					durationToAcceptResponses = 0,
					consoleMessage = new()
					{text = "Is UAV 11 headed for the NFZ?",
					color = "red"},
					acceptMultipleResponses = false,
					responseOptions = new List<ResponseOption>()
					{
						new ()
						{
							buttonText = "Yes",
							isCorrectResponse = false
						},
						new ()
						{
							buttonText = "No",
							isCorrectResponse = true
						},
						new ()
						{
							buttonText = "Pass",
							isCorrectResponse = false
						}
					}
				},
				new()
				{
					timeToPresent = 161,
					durationToAcceptResponses = 0,
					consoleMessage = new()
						{
					text = "Which UAV/s had a bad projected route?",
					color = "red",
					},
					acceptMultipleResponses = true,
					responseOptions = new List<ResponseOption>()
					{
						new() { buttonText = "#0"  },
						new () { buttonText = "#1" },
						new () { buttonText = "#2" },
						new () { buttonText = "#3" },
						new () { buttonText = "#4" },
						new () { buttonText = "#5" },
						new () { buttonText = "#6" },
						new () { buttonText = "#7" },
						new () { buttonText = "#8" },
						new () { buttonText = "#9" },
						new () { buttonText = "#10", isCorrectResponse = true },
						new () { buttonText = "#11" },
						new () { buttonText = "#12" },
						new () { buttonText = "#13" },
						new () { buttonText = "#14" },
						new () { buttonText = "#15" },
						
					}
				},
				new()
				{
					timeToPresent = 204,
					durationToAcceptResponses = 0,
					consoleMessage = new()
					{
					text = "Detecting semi-transparent targets?"
					},
					acceptMultipleResponses = false,
					responseOptions = new List<ResponseOption>()
					{
						new ()
						{
							buttonText = "Confirm",
							isCorrectResponse = true
						},
						new ()
						{
							buttonText = "Deny",
							isCorrectResponse = false
						},
						new ()
						{
							buttonText = "Multiple",
							isCorrectResponse = true
						}
					}
				},
				new()
				{
					timeToPresent = 389,
					durationToAcceptResponses = 0,
					consoleMessage = new()
					{
						text = "Have all UAVs detected at least one target?",
						color = "Yellow"
					},
					acceptMultipleResponses = false,
					responseOptions = new List<ResponseOption>()
					{
						new ()
						{
							buttonText = "Yes",
							isCorrectResponse = true
						},
						new ()
						{
							buttonText = "No",
							isCorrectResponse = false
						},
					}
				},
				//414	2	Detected a FL for UAV 4  - Respond (Confirm/Deny)	Confirm
				new()
				{
					timeToPresent=414,
					durationToAcceptResponses=0,
					consoleMessage = new()
					{
					text="Detected a FL for UAV 4?"
					
					},
					acceptMultipleResponses=false,
					responseOptions=new List<ResponseOption>()
					{
						new()
						{
							buttonText="Confirm",
							isCorrectResponse=true
						},
						new()
						{
							buttonText="Deny",
							isCorrectResponse=false
						},
					}
				},
				// 492	3	Status update for the projected route for UAV 9 - Respond (Good/Bad)	Good
				new()
				{
					timeToPresent=492,
					durationToAcceptResponses=0,
					consoleMessage = new()
					{
					text="Status update for the projected route for UAV 9?"},
					acceptMultipleResponses=false,
					responseOptions=new List<ResponseOption>()
					{
						new()
						{
							buttonText="Good",
							isCorrectResponse=true
						},
						new()
						{
							buttonText="Bad",
							isCorrectResponse=false
						},
					}
				},
				// 566	1	Did UAV 3 experience a FL? - Respond (Yes/No)	No
				new()
				{
					timeToPresent=566,
					durationToAcceptResponses=0,
					consoleMessage = new() {text="Did UAV 3 experience a FL?"},
					acceptMultipleResponses=false,
					responseOptions=new List<ResponseOption>()
					{
						new()
						{
							buttonText="Yes",
							isCorrectResponse=false
						},
						new()
						{
							buttonText="No",
							isCorrectResponse=true
						},
					}
				},
				// 602	2	Detecting ground vehicles in mission- Respond (Confirm/Deny)	Deny
				new()
				{
					timeToPresent=602,
					durationToAcceptResponses=0,
					consoleMessage = new()
					{text="Detecting ground vehicles in mission?"},
					acceptMultipleResponses=false,
					responseOptions=new List<ResponseOption>()
					{
						new()
						{
							buttonText="Confirm",
							isCorrectResponse=false
						},
						new()
						{
							buttonText="Deny",
							isCorrectResponse=true
						},
					}
				},
				// 649	1	Was UAV 6 ever headed for the NFZ? - Respond (Yes/No)	Yes
				new()
				{
					timeToPresent=649,
					durationToAcceptResponses=0,
					consoleMessage = new()
					{text="Was UAV 6 ever headed for the NFZ?"},
					acceptMultipleResponses=false,
					responseOptions=new List<ResponseOption>()
					{
						new()
						{
							buttonText="Yes",
							isCorrectResponse=true
						},
						new()
						{
							buttonText="No",
							isCorrectResponse=false
						},
					}
				},
				// 672	3	Status update for the video feed of UAV 15 - Respond (Good/Bad)	Good
				new()
				{
					timeToPresent=672,
					durationToAcceptResponses=0,
					consoleMessage = new()
					{text="Status update for the video feed of UAV 15?"},
					acceptMultipleResponses=false,
					responseOptions=new List<ResponseOption>()
					{
						new()
						{
							buttonText="Good",
							isCorrectResponse=true
						},
						new()
						{
							buttonText="Bad",
							isCorrectResponse=false
						},
					}
				},
				// 819	1	Was UAV 13 ever headed for the NFZ? - Respond (Yes/No)	No
				new()
				{
					timeToPresent=819,
					durationToAcceptResponses=0,
					consoleMessage = new()
					{text="Was UAV 13 ever headed for the NFZ?"},
					acceptMultipleResponses=false,
					responseOptions=new List<ResponseOption>()
					{
						new()
						{
							buttonText="Yes",
							isCorrectResponse=false
						},
						new()
						{
							buttonText="No",
							isCorrectResponse=true
						},
					}
				},
				// 884	2	Detecting less than ten active UAVs - Respond (Confirm/Deny)	Deny
				new()
				{
					timeToPresent=884,
					durationToAcceptResponses=0,
					consoleMessage = new()
					{text="Detecting less than ten active UAVs?"},
					acceptMultipleResponses=false,
					responseOptions=new List<ResponseOption>()
					{
						new()
						{
							buttonText="Confirm",
							isCorrectResponse=false
						},
						new()
						{
							buttonText="Deny",
							isCorrectResponse=true
						},
					}
				},

			};

			return messages;
		}
	}
}